apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-dod-jf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-dod-jf
  template:
    metadata:
      labels:
        app: app-dod-jf
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: type
                operator: In
                values:
                - app-dod-jf
      containers:
        - name: app-dod-jf
          image: danielrodriguess/app-dod-jf:v1
          resources:
            requests:
              cpu: 32m
              memory: 64Mi
            limits:
              cpu: 64m
              memory: 100Mi
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 2
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
            successThreshold: 1
          ports:
          - containerPort: 3000