apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: app-dod-jf-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: app-dod-jf
    kind: Deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25